/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quancafe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author sniper dracula
 */
public class NhanVien extends javax.swing.JFrame {
    private DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form NhanVien
     */
    public NhanVien() {
        //System.out.print("toi nhan vien");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        cmbnamsinh = new javax.swing.JComboBox<>();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtadc = new javax.swing.JTextArea();
        txtsdt = new javax.swing.JTextField();
        txtluong = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnchon = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        cmbtimkiem = new javax.swing.JComboBox<>();
        txtTimTen = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        btnin1 = new javax.swing.JButton();
        btndangxuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lí Nhân Viên");
        setBackground(new java.awt.Color(0, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lí Nhân Viên");

        jLabel2.setText("Mã Nhân Viên: ");

        jLabel3.setText("Họ Tên: ");

        jLabel4.setText("Năm Sinh: ");

        jLabel5.setText("Giới Tính: ");

        jLabel6.setText("Số DT: ");

        jLabel7.setText("Địa Chỉ: ");

        jLabel8.setText("Lương: ");

        txtMaNV.setEnabled(false);

        cmbnamsinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996" }));

        btng.add(rbtnNam);
        rbtnNam.setText("Nam");

        btng.add(rbtnNu);
        rbtnNu.setText("Nữ");

        txtadc.setColumns(20);
        txtadc.setRows(5);
        jScrollPane2.setViewportView(txtadc);

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtnNam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnNu))
                                    .addComponent(cmbnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(25, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnsua)
                                .addGap(18, 18, 18)
                                .addComponent(btnluu)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnNam)
                            .addComponent(rbtnNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnluu)
                    .addComponent(btnsua))
                .addContainerGap())
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MaNV", "HoTen", "NamSinh", "GioiTinh", "DiaChi", "SDT", "Luong"
            }
        ));
        jScrollPane1.setViewportView(table);

        btnchon.setText("Xem");
        btnchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchonActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        cmbtimkiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo Tên", "Theo Mã" }));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        btnin.setText("In DS");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        btnin1.setText("In 1 NV");
        btnin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnchon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cmbtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtTimTen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnthoat)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTimTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnchon)
                    .addComponent(btnThem)
                    .addComponent(btnxoa)
                    .addComponent(btnin)
                    .addComponent(btnin1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnthoat))
        );

        btndangxuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\sniper dracula\\Pictures\\exit2.PNG")); // NOI18N
        btndangxuat.setPreferredSize(new java.awt.Dimension(15, 15));
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btndangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadtable(){
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            String dbUrl = "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";

            Connection con = DriverManager.getConnection(dbUrl);

            Statement s = con.createStatement();

            ResultSet rs = s.executeQuery("select * from NhanVien");

          

             String []colsName = {"Mã Nhân Viên", "Họ Tên", "Năm Sinh", "Giới Tính","Địa Chỉ","Số ĐT","Lương"
                     + ""};

            tableModel.setColumnIdentifiers(colsName); // Đặt tiêu đề cho bảng theo các giá trị của mảng colsName

 

            table.setModel(tableModel);

         

            while(rs.next()){ // nếu còn đọc tiếp được một dòng dữ liệu

                Object rows[] = new Object[7];

                rows[0] = rs.getString(1);

                rows[1] = rs.getString(2);

                rows[2] = rs.getInt(3);

                rows[3] = rs.getString(4);
                
                rows[4] = rs.getString(5);

                rows[5] = rs.getInt(6);

                rows[6] = rs.getInt(7);

                tableModel.addRow(rows);

 

            }

            con.close();
            
           
            
            

        } catch (Exception ex) {

            ex.printStackTrace();

        }
    }
    
    private String fill3char(int x){
        String res = String.valueOf(x);
        while(res.length() < 3){
            res = "0" + res;
        }
        return res;
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadtable();
        txtHoTen.setEnabled(false);
        cmbnamsinh.setEnabled(false);
        rbtnNam.setEnabled(false);
        rbtnNu.setEnabled(false);
        txtadc.setEnabled(false);
        txtsdt.setEnabled(false);
        txtluong.setEnabled(false);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_formWindowActivated
    private void chonnut(){
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            String dbUrl = "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";

            Connection con = DriverManager.getConnection(dbUrl);

            Statement s = con.createStatement();
            int n=0;
            String nsi [] = {"1990","1991","1992","1993","1994","1995","1996"};
            int r=table.getSelectedRow();
            Object id=tableModel.getValueAt(r,0);
            Object hoten= tableModel.getValueAt(r, 1);
            Object ns = tableModel.getValueAt(r, 2);
            Object gt =tableModel.getValueAt(r, 3);
            Object dc= tableModel.getValueAt(r, 4);
            Object sdt = tableModel.getValueAt(r, 5);
            Object l =tableModel.getValueAt(r, 6);
            txtMaNV.setText(""+id);
            txtHoTen.setText(""+hoten);
            if (ns.toString().equals("1990")){
                n=1990;
            }
            else if (ns.toString().equals("1991")){
                n=1991;
            }
            else if(ns.toString().equals("1992")){
                n=1992;
            }
            else if(ns.toString().equals("1993")){
                n=1993;
            }
            else if(ns.toString().equals("1994")){
                n=1994;
            }
            else if (ns.toString().equals("1995")){
                n=1995;
            }
            else {n=1996;}
            //System.out.print(""+n);
            switch(n){
                case 1990: cmbnamsinh.setSelectedIndex(0);break;
                case 1991: cmbnamsinh.setSelectedIndex(1);break;
                case 1992: cmbnamsinh.setSelectedIndex(2);break;
                case 1993: cmbnamsinh.setSelectedIndex(3);break;
                case 1994: cmbnamsinh.setSelectedIndex(4);break;
                case 1995: cmbnamsinh.setSelectedIndex(5);break;
                case 1996: cmbnamsinh.setSelectedIndex(6);break;
            }
            String gio="nam";
            if (gio.toLowerCase().equals(gt.toString().toLowerCase())){
                rbtnNam.setSelected(true);
            }
            else {rbtnNu.setSelected(true);}
            txtadc.setText(""+dc);
            txtsdt.setText(""+sdt);
            txtluong.setText(""+l);
            con.close();

        } catch (Exception ex) {

            ex.printStackTrace();

        }
    }
    private void btnchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchonActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        chonnut();
    }//GEN-LAST:event_btnchonActionPerformed
    private void xetthem(int i){
        String ma = "", mam = "";
         int r=table.getRowCount();
         //System.out.print(""+r);
         ma=tableModel.getValueAt(r-1, 0).toString();
         //System.out.print(""+ma);
         mam = "NV" + fill3char(Integer.valueOf(ma.substring(2)) + 1+i);
            
         txtMaNV.setText(mam);
         txtHoTen.setText("");
         cmbnamsinh.setSelectedIndex(0);
         //rbtnNam.setSelected(false);
         rbtnNu.setSelected(false);
         txtadc.setText("");
         txtsdt.setText("");
         txtluong.setText("");
    }
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        if(txtHoTen.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Sai Dữ Liệu");
           
        }else{
            try{
               System.out.print("sda");
                int n;
                n = Integer.parseInt(txtsdt.getText());
                System.out.print("sda");
            } catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null,"Loi: SDT phai nhap la so");
            } catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Loi: " + ex.getMessage());
            }
            try{
               System.out.print("sda");
                int n;
                n = Integer.parseInt(txtluong.getText());
                System.out.print("sda");
            } catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null,"Loi: Luong phai nhap la so");
            } catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Loi: " + ex.getMessage());
            }
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            String dbUrl = "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";

            Connection con = DriverManager.getConnection(dbUrl);

            Statement s = con.createStatement();
            int r=table.getSelectedRow();
            int rn=table.getRowCount();
            //Object id=tableModel.getValueAt(r,0);
            //Object hoten= tableModel.getValueAt(r, 1);
            String id =txtMaNV.getText();
            String hoten= txtHoTen.getText();
            int ns = Integer.parseInt(cmbnamsinh.getSelectedItem().toString());
            //System.out.print(""+ns);
            String xetgt="nam";
            String gt="";
            if(rbtnNam.isSelected()==true){
                gt=xetgt;
            }else {gt="nu";}
            String dc=txtadc.getText();
            int sdt=Integer.parseInt(txtsdt.getText());
            int l=Integer.parseInt(txtluong.getText());
            //System.out.print("Da den day");
            //System.out.print(""+id);
            System.out.print(""+tableModel.getValueAt(r, 0));
            if (id.equals(tableModel.getValueAt(r, 0))){
               String up = "update NhanVien set HoTen='" + hoten +"',NamSinh="+ns+",GioiTinh='"+gt+"',DiaChi='"+dc+"',SDT="+sdt+",Luong="+l+ "where MaNV='" +id+"'";
               s.execute(up);
               xetthem(0);
            }
            else {
                //System.out.println("da chon");
                String up = "INSERT INTO NhanVien VALUES ('"+id+"','"+hoten+"',"+ns+",'"+gt+"','"+dc+"',"+sdt+","+l+")";
                s.execute(up);
                xetthem(1);
            }
                //System.out.println(up);
                JOptionPane.showMessageDialog(null, "Luu Thanh Cong");
                for (int k=rn-1;k>=0;k--){
                    tableModel.removeRow(k);
                }
                //loadtable();
            //btnThemActionPerformed(evt);
            
            con.close();
        } catch (Exception ex) {

            ex.printStackTrace();

        }
        }
    }//GEN-LAST:event_btnluuActionPerformed
    private void timkiemten(){
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            String dbUrl = "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";

            Connection con = DriverManager.getConnection(dbUrl);

            Statement s = con.createStatement();
            int r=table.getRowCount();
            List<Integer> arr2del= new LinkedList<>();
            String item="",kword=txtTimTen.getText().toLowerCase();
            for (int i=0;i<r;i++){
                item = tableModel.getValueAt(i, 1).toString().toLowerCase();
                if(kword.trim().compareTo("")!=0 && item.indexOf(kword)==-1){
                    arr2del.add(i);
                }
            }
            
            for (int j=arr2del.size()-1;0<=j;--j){
                tableModel.removeRow(arr2del.get(j));
            }
            con.close();

        } catch (Exception ex) {

            ex.printStackTrace();

        }
    }
    private void timkiemma(){
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            String dbUrl = "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";

            Connection con = DriverManager.getConnection(dbUrl);

            Statement s = con.createStatement();
            int r=table.getRowCount();
            List<Integer> arr2del= new LinkedList<>();
            String item="",kword=txtTimTen.getText().toLowerCase();
            for (int i=0;i<r;i++){
                item = tableModel.getValueAt(i, 0).toString().toLowerCase();
                if(kword.trim().compareTo("")!=0 && item.indexOf(kword)==-1){
                    arr2del.add(i);
                }
            }
            
            for (int j=arr2del.size()-1;0<=j;--j){
                tableModel.removeRow(arr2del.get(j));
            }
            con.close();

        } catch (Exception ex) {

            ex.printStackTrace();

        }
    }
    private void removerow(){
        int r=table.getRowCount();
        for (int j=r-1;j>=0;j--){
            tableModel.removeRow(j);
        }
    }
    int i=0;
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        //loadtable();
        //System.out.print(""+cmbtimkiem.getSelectedIndex());
        if (txtTimTen.getText().equals("")){
            int r=table.getRowCount();
            System.out.print(""+r);
            for (int j=r-1;j>=0;j--){
                tableModel.removeRow(j);
            }
            i=0;
            loadtable();
        }
        if (cmbtimkiem.getSelectedIndex()==0){
            timkiemten();
            if (i>0){
                removerow();
                loadtable();
                timkiemten();
            }
            //timkiemten();
        }
        else if (cmbtimkiem.getSelectedIndex()==1){
            timkiemma();
            //System.out.print(""+i);
            if (i>0){
                removerow();
                loadtable();
                timkiemma();
            }
        }
        i++;
    }//GEN-LAST:event_btnTimKiemActionPerformed
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtHoTen.setEnabled(true);
        cmbnamsinh.setEnabled(true);
        rbtnNam.setEnabled(true);
        rbtnNu.setEnabled(true);
        txtadc.setEnabled(true);
        txtsdt.setEnabled(true);
        txtluong.setEnabled(true);
         xetthem(0);
         jPanel1.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int output = JOptionPane.showConfirmDialog(null
               , "Ban co muon xoa"
               ,"Quan Li Quan Cafe"
               ,JOptionPane.YES_NO_OPTION);

            if(output == JOptionPane.YES_OPTION){
               
        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            String dbUrl = "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";

            Connection con = DriverManager.getConnection(dbUrl);

            Statement s = con.createStatement();
            int rn=table.getRowCount();
            int r=table.getSelectedRow();
            Object id= tableModel.getValueAt(r, 0);
            String up = "DELETE From NhanVien where MaNV='"+id+"'";
            s.execute(up);
            JOptionPane.showMessageDialog(null, "Xoa Thanh Cong");
            for (int k=rn-1;k>=0;k--){
                    tableModel.removeRow(k);
                }
            con.close();
        } catch (Exception ex) {

            ex.printStackTrace();

        }
        //System.out.print("Yes selected.");
            }else if(output == JOptionPane.NO_OPTION){
               jPanel2.show();
            }
        
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        txtHoTen.setEnabled(true);
        cmbnamsinh.setEnabled(true);
        rbtnNam.setEnabled(true);
        rbtnNu.setEnabled(true);
        txtadc.setEnabled(true);
        txtsdt.setEnabled(true);
        txtluong.setEnabled(true);
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        // TODO add your handling code here:
        new Menu().show();
        this.hide();
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        // TODO add your handling code here:
     
        try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl= "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";
                Connection con=DriverManager.getConnection(dbUrl);
                //String link = "C:\\Users\\sniper dracula\\Documents\\NetBeansProjects\\Quancafe\\src\\quancafe\\report1.jrxml";
                JasperDesign jd= JRXmlLoader.load("C:\\Users\\sniper dracula\\Documents\\NetBeansProjects\\Quancafe\\src\\quancafe\\report2.jrxml");
                String sql = "select * from NhanVien";
                JRDesignQuery newq = new JRDesignQuery();
                newq.setText(sql);
                jd.setQuery(newq);
                JasperReport rs=JasperCompileManager.compileReport(jd);
                JasperPrint pri = JasperFillManager.fillReport(rs,null,con);
                JasperViewer.viewReport(pri);
                
                con.close();
        }catch(Exception ex){
                ex.printStackTrace();
        }
    
    }//GEN-LAST:event_btninActionPerformed
    private void inhoadon(String sqlsv){
        try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl= "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";
                Connection con=DriverManager.getConnection(dbUrl);
                //String link = "C:\\Users\\sniper dracula\\Documents\\NetBeansProjects\\Quancafe\\src\\quancafe\\report1.jrxml";
                JasperDesign jd= JRXmlLoader.load("C:\\Users\\sniper dracula\\Documents\\NetBeansProjects\\Quancafe\\src\\quancafe\\report2.jrxml");
                String sql = sqlsv;
                JRDesignQuery newq = new JRDesignQuery();
                newq.setText(sql);
                jd.setQuery(newq);
                JasperReport rs=JasperCompileManager.compileReport(jd);
                JasperPrint pri = JasperFillManager.fillReport(rs,null,con);
                JasperViewer.viewReport(pri);
                
                con.close();
        }catch(Exception ex){
                ex.printStackTrace();
        }
    }
    private void btnin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnin1ActionPerformed
        // TODO add your handling code here:                        
        int r=table.getSelectedRow();
        Object id=table.getValueAt(r, 0);
        //System.out.print(""+maban);
        String link="select * from NhanVien where MaNV='"+id+"'";
        inhoadon(link);
        //new NhanVien().show();
    }//GEN-LAST:event_btnin1ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnchon;
    private javax.swing.JButton btndangxuat;
    private javax.swing.ButtonGroup btng;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnin1;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cmbnamsinh;
    private javax.swing.JComboBox<String> cmbtimkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTimTen;
    private javax.swing.JTextArea txtadc;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
