/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quancafe;
import java.awt.Color;
import java.sql.*;
import java.sql.DriverManager;
import java.util.Scanner;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author sniper dracula
 */
public class Quanli extends javax.swing.JFrame {
        private int sx[]={0,1,2,3,4,5};
        //int /*tien1=0,tien2=0,tien3=0,tien4=0,tien5=0,*/tien[];
        private String loainuoc[]={"chua goi","nuoc cam" , "tra sua","cafe","cafe sua","coca cola"};
        private String sl[]={"0","1","2","3","4","5"};
        private int tiennuoc[]={0,10000,8000,12000,9000,11000};
        private int soluong[]={0,0,0,0,0};
        private int tiennuoctt[]={0,0,0,0,0};

    /**
     * Creates new form Quanli
     */
    public Quanli() {
        System.out.print("da toi");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnxanh = new javax.swing.JButton();
        btntrang = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmaban = new javax.swing.JTextField();
        cmbsoloainuoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbmenu1 = new javax.swing.JComboBox<>();
        cmbsoluong1 = new javax.swing.JComboBox<>();
        lbtinhtien = new javax.swing.JLabel();
        cmbsoluong2 = new javax.swing.JComboBox<>();
        cmbmenu2 = new javax.swing.JComboBox<>();
        cmbsoluong3 = new javax.swing.JComboBox<>();
        cmbmenu3 = new javax.swing.JComboBox<>();
        cmbsoluong4 = new javax.swing.JComboBox<>();
        cmbmenu4 = new javax.swing.JComboBox<>();
        cmbsoluong5 = new javax.swing.JComboBox<>();
        cmbmenu5 = new javax.swing.JComboBox<>();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        btninhoadon = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btndangxuat = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lí Quán Cafe");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel17.setText("Bàn chưa có khách ngồi");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        btn1.setText("01");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("02");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn4.setText("04");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn3.setText("03");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn7.setText("07");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("08");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn6.setText("06");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setText("05");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn9.setText("09");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn12.setText("12");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn11.setText("11");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn10.setText("10");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn15.setText("15");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.setText("16");
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        btn14.setText("14");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn13.setText("13");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4)))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5)
                    .addComponent(btn6)
                    .addComponent(btn7)
                    .addComponent(btn8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn9)
                    .addComponent(btn10)
                    .addComponent(btn11)
                    .addComponent(btn12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn13)
                    .addComponent(btn14)
                    .addComponent(btn15)
                    .addComponent(btn16))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("Số Bàn");

        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("Chọn số bàn tương ứng để hiển thị thông tin");

        btnxanh.setText("xanh");

        btntrang.setBackground(new java.awt.Color(0, 0, 0));
        btntrang.setText("Đen");
        btntrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrangActionPerformed(evt);
            }
        });

        jLabel16.setText("Bàn đã có khách ngồi");

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel2.setText("Mã Bàn: ");

        jLabel3.setText("Số Loại Nước: ");

        txtmaban.setEnabled(false);

        cmbsoloainuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cmbsoloainuoc.setEnabled(false);

        jLabel4.setText("Loại 1: ");

        jLabel5.setText("Loại 2: ");

        jLabel6.setText("Loại 3: ");

        jLabel7.setText("Loại 4: ");

        jLabel8.setText("Loại 5: ");

        cmbmenu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chua goi", "nuoc cam", "tra sua", "cafe", "cafe sua", "coca cola" }));

        cmbsoluong1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbsoluong2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbmenu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chua goi", "nuoc cam", "tra sua", "cafe", "cafe sua", "coca cola" }));

        cmbsoluong3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbmenu3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chua goi", "nuoc cam", "tra sua", "cafe", "cafe sua", "coca cola" }));

        cmbsoluong4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbmenu4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chua goi", "nuoc cam", "tra sua", "cafe", "cafe sua", "coca cola" }));

        cmbsoluong5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));

        cmbmenu5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chua goi", "nuoc cam", "tra sua", "cafe", "cafe sua", "coca cola" }));

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btninhoadon.setText("In Hóa Đơn");
        btninhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninhoadonActionPerformed(evt);
            }
        });

        jLabel9.setText("Số Lượng");

        jLabel10.setText("Số Lượng");

        jLabel11.setText("Số Lượng");

        jLabel12.setText("Số Lượng");

        jLabel13.setText("Số Lượng");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbsoluong5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbmenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbsoluong4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbsoluong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbsoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbtinhtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbsoloainuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtmaban, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnthem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnluu)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnxoa)
                                        .addGap(30, 30, 30)
                                        .addComponent(btninhoadon)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmaban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbsoloainuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtinhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbsoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbsoluong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbmenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbsoluong4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbmenu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbsoluong5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbmenu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnluu)
                    .addComponent(btninhoadon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btndangxuat.setIcon(new javax.swing.ImageIcon("C:\\Users\\sniper dracula\\Pictures\\exit2.PNG")); // NOI18N
        btndangxuat.setPreferredSize(new java.awt.Dimension(15, 15));
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });

        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Quản Lí Gọi Nước - Quán Cafe");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel1)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnxanh)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btntrang)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnthoat)
                .addGap(60, 60, 60))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(63, 63, 63)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnxanh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntrang)
                    .addComponent(jLabel17))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(btndangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnthoat)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void connectban(int a){
        jPanel2.setVisible(true);
        try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl= "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";
                Connection con=DriverManager.getConnection(dbUrl);
                //System.out.print("aaaa");
                Statement so= con.createStatement();
                String cu="select * from QuanliQuan where MaBan="+a;
                ResultSet rs = so.executeQuery(cu);
                
                //System.out.print("aaaa");
           while(rs.next()){
               txtmaban.setText(""+rs.getInt(1));
               //System.out.print(""+rs.getInt(2));
               if (rs.getInt(2)==0){
                   cmbsoloainuoc.setSelectedIndex(0);
               }
               else if(rs.getInt(2)==1){
                   cmbsoloainuoc.setSelectedIndex(1);
               }
               else if(rs.getInt(2)==2){
                   cmbsoloainuoc.setSelectedIndex(2);
               }
               else if(rs.getInt(2)==3){
                   cmbsoloainuoc.setSelectedIndex(3);
               }
               else if(rs.getInt(2)==4){
                   cmbsoloainuoc.setSelectedIndex(4);
               }
               else cmbsoloainuoc.setSelectedIndex(5);
               //
               //xu li cac goi mon
               for (int i=0;i<=5;i++){
                   if (rs.getString(3).equals(loainuoc[i]))
                       cmbmenu1.setSelectedIndex(i);
                   if (rs.getString(5).equals(loainuoc[i]))
                       cmbmenu2.setSelectedIndex(i);
                   if (rs.getString(7).equals(loainuoc[i]))
                       cmbmenu3.setSelectedIndex(i);
                   if (rs.getString(9).equals(loainuoc[i]))
                       cmbmenu4.setSelectedIndex(i);
                   if (rs.getString(11).equals(loainuoc[i]))
                       cmbmenu5.setSelectedIndex(i);
               }
               for (int j=0;j<=5;j++){
                   if (rs.getInt(4)==sx[j])
                       cmbsoluong1.setSelectedIndex(j);
                   if (rs.getInt(6)==sx[j])
                       cmbsoluong2.setSelectedIndex(j);
                   if (rs.getInt(8)==sx[j])
                       cmbsoluong3.setSelectedIndex(j);
                   if (rs.getInt(10)==sx[j])
                       cmbsoluong4.setSelectedIndex(j);
                   if (rs.getInt(12)==sx[j])
                       cmbsoluong5.setSelectedIndex(j);
               }
               
               //cmbsoloainuoc.setSelectedIndex(2);
                //System.out.println("DVDCodeNo "+rs.getInt(1));
            }
            con.close();
            this.xetsoluong();
        }catch(Exception ex){
                ex.printStackTrace();
        }
        
    
    }
    public void loadban(){
        //jPanel2.hide();
    }
    private void unmahoa(){
            cmbmenu1.setEnabled(true);
            cmbsoluong1.setEnabled(true);
            cmbmenu2.setEnabled(true);
            cmbsoluong2.setEnabled(true);
            cmbmenu3.setEnabled(true);
            cmbsoluong3.setEnabled(true);
            cmbmenu4.setEnabled(true);
            cmbsoluong4.setEnabled(true);
            cmbmenu5.setEnabled(true);
            cmbsoluong5.setEnabled(true);
            btnthem.setEnabled(true);
            btnxoa.setEnabled(true);
            btnluu.setEnabled(true);
            btninhoadon.setEnabled(true);
    }
    private int hamtam(){
        
        int tongtien=0;
        int n=0;
        
      //  int tong[]={0,0,0,0,0,0};
       // int tiennuoc1,tiennuoc2,tiennuoc3,tiennuoc4,tiennuoc5;
       
       if (cmbsoloainuoc.getSelectedItem().equals(sl[0]))
           n=0;
       else if(cmbsoloainuoc.getSelectedItem().equals(sl[1]))
           n=1;
       else if(cmbsoloainuoc.getSelectedItem().equals(sl[2]))
           n=2;
       else if(cmbsoloainuoc.getSelectedItem().equals(sl[3]))
           n=3;
       else if(cmbsoloainuoc.getSelectedItem().equals(sl[4]))
           n=4;
       else n=5;
       
       //tien nuoc
       for (int j=0;j<=5;j++){
                if (cmbmenu1.getSelectedItem().equals(loainuoc[j]))
                    tiennuoctt[0]=tiennuoc[j];
                if (cmbmenu2.getSelectedItem().equals(loainuoc[j]))
                    tiennuoctt[1]=tiennuoc[j];
                if (cmbmenu3.getSelectedItem().equals(loainuoc[j]))
                    tiennuoctt[2]=tiennuoc[j];
                if (cmbmenu4.getSelectedItem().equals(loainuoc[j]))
                    tiennuoctt[3]=tiennuoc[j];
                if (cmbmenu5.getSelectedItem().equals(loainuoc[j]))
                    tiennuoctt[4]=tiennuoc[j];
            }
      
           for (int j=0;j<=5;j++){
                if (cmbsoluong1.getSelectedItem().equals(sl[j]))
                    soluong[0]=j;
                if (cmbsoluong2.getSelectedItem().equals(sl[j]))
                    soluong[1]=j;
                if (cmbsoluong3.getSelectedItem().equals(sl[j]))
                    soluong[2]=j;
                if (cmbsoluong4.getSelectedItem().equals(sl[j]))
                    soluong[3]=j;
                if (cmbsoluong5.getSelectedItem().equals(sl[j]))
                    soluong[4]=j;
            }
          
       for (int m=0;m<5;m++){
           tongtien+=soluong[m]*tiennuoctt[m];
       }
           return tongtien;
//       
//       if (cmbsoloainuoc.getSelectedItem().equals("0")){
//           JOptionPane.showMessageDialog(null, "Không Có Dữ Liệu");
//       }
//       if (cmbsoloainuoc.getSelectedItem().equals("1")){
//           int output = JOptionPane.showConfirmDialog(null
//               , "********Quan Cafe Vip********\n>>>>>>Hóa Đơn Tiền Nước\n------------------\n Bàn Số: "+txtmaban.getText()+"\n-------------------\n | Loại Nước: "+cmbmenu1.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong1.getSelectedItem()+ "  | Giá: "+(soluong[0]*tiennuoctt[0])+" |\n----------------\n Tổng Tiền: "+(soluong[0]*tiennuoctt[0])+"\n\nChúc Quý Khách Vui Vẻ"  
//               ,"Quan Li Quan Cafe"
//               ,JOptionPane.YES_NO_OPTION);
//            if(output == JOptionPane.YES_OPTION){
//        JOptionPane.showMessageDialog(null, "In Thanh Cong!!!");
//            }else if(output == JOptionPane.NO_OPTION){
//               jPanel2.show();
//            }
//       }
//       if (cmbsoloainuoc.getSelectedItem().equals("2")){
//           int output = JOptionPane.showConfirmDialog(null
//               , "********Quan Cafe Vip********\n>>>>>>Hóa Đơn Tiền Nước\n------------------\n Bàn Số: "+txtmaban.getText()+"\n-------------------\n | Loại Nước: "+cmbmenu1.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong1.getSelectedItem()+ "  | Giá: "+(soluong[0]*tiennuoctt[0])+" |\n-------------------\n | Loại Nước: "+cmbmenu2.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong2.getSelectedItem()+ "  | Giá: "+(soluong[1]*tiennuoctt[1])+" |\n----------------\n Tổng Tiền: "+(soluong[0]*tiennuoctt[0]+soluong[1]*tiennuoctt[1])+"\n\nChúc Quý Khách Vui Vẻ"  
//                   
//               ,"Quan Li Quan Cafe"
//               ,JOptionPane.YES_NO_OPTION);
//            if(output == JOptionPane.YES_OPTION){
//        JOptionPane.showMessageDialog(null, "In Thanh Cong!!!");
//            }else if(output == JOptionPane.NO_OPTION){
//               jPanel2.show();
//            }
//       }
//       if (cmbsoloainuoc.getSelectedItem().equals("3")){
//           int output = JOptionPane.showConfirmDialog(null
//               , "********Quan Cafe Vip********\n>>>>>>Hóa Đơn Tiền Nước\n------------------\n Bàn Số: "+txtmaban.getText()+"\n-------------------\n | Loại Nước: "+cmbmenu1.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong1.getSelectedItem()+ "  | Giá: "+(soluong[0]*tiennuoctt[0])+" |\n-------------------\n | Loại Nước: "+cmbmenu2.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong2.getSelectedItem()+ "  | Giá: "+(soluong[1]*tiennuoctt[1])+" |\n-------------------\n | Loại Nước: "+cmbmenu3.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong3.getSelectedItem()+ "  | Giá: "+(soluong[2]*tiennuoctt[2])+" |\n----------------\n Tổng Tiền: "+(soluong[0]*tiennuoctt[0]+soluong[1]*tiennuoctt[1]+soluong[2]*tiennuoctt[2])+"\n\nChúc Quý Khách Vui Vẻ"  
//                   
//               ,"Quan Li Quan Cafe"
//               ,JOptionPane.YES_NO_OPTION);
//            if(output == JOptionPane.YES_OPTION){
//        JOptionPane.showMessageDialog(null, "In Thanh Cong!!!");
//            }else if(output == JOptionPane.NO_OPTION){
//               jPanel2.show();
//            }
//       }
//       if (cmbsoloainuoc.getSelectedItem().equals("4")){
//           int output = JOptionPane.showConfirmDialog(null
//               , "********Quan Cafe Vip********\n>>>>>>Hóa Đơn Tiền Nước\n------------------\n Bàn Số: "+txtmaban.getText()+"\n-------------------\n | Loại Nước: "+cmbmenu1.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong1.getSelectedItem()+ "  | Giá: "+(soluong[0]*tiennuoctt[0])+" |\n-------------------\n | Loại Nước: "+cmbmenu2.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong2.getSelectedItem()+ "  | Giá: "+(soluong[1]*tiennuoctt[1])+" |\n-------------------\n | Loại Nước: "+cmbmenu3.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong3.getSelectedItem()+ "  | Giá: "+(soluong[2]*tiennuoctt[2])+" |\n-------------------\n | Loại Nước: "+cmbmenu4.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong4.getSelectedItem()+ "  | Giá: "+(soluong[3]*tiennuoctt[3])+" |\n----------------\n Tổng Tiền: "+(soluong[0]*tiennuoctt[0]+soluong[1]*tiennuoctt[1]+soluong[2]*tiennuoctt[2]+soluong[3]*tiennuoctt[3])+"\n\nChúc Quý Khách Vui Vẻ"  
//                   
//               ,"Quan Li Quan Cafe"
//               ,JOptionPane.YES_NO_OPTION);
//            if(output == JOptionPane.YES_OPTION){
//        JOptionPane.showMessageDialog(null, "In Thanh Cong!!!");
//            }else if(output == JOptionPane.NO_OPTION){
//               jPanel2.show();
//            }
//       }
//       if (cmbsoloainuoc.getSelectedItem().equals("5")){
//           int output = JOptionPane.showConfirmDialog(null
//               , "********Quán Cafe Vip********\n>>>>>>Hóa Đơn Tiền Nước\n------------------------------------------------------------------------\n Bàn Số: "+txtmaban.getText()+"\n-------------------------------------------------------------------------\n | Loại Nước: "+cmbmenu1.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong1.getSelectedItem()+ "  | Giá: "+(soluong[0]*tiennuoctt[0])+" |\n-------------------------------------------------------------------------\n | Loại Nước: "+cmbmenu2.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong2.getSelectedItem()+ "  | Giá: "+(soluong[1]*tiennuoctt[1])+" |\n-------------------------------------------------------------------------\n | Loại Nước: "+cmbmenu3.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong3.getSelectedItem()+ "  | Giá: "+(soluong[2]*tiennuoctt[2])+" |\n-------------------------------------------------------------------------\n | Loại Nước: "+cmbmenu4.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong4.getSelectedItem()+ "  | Giá: "+(soluong[3]*tiennuoctt[3])+" |\n-------------------------------------------------------------------------\n | Loại Nước: "+cmbmenu5.getSelectedItem()+"  | Số Lượng: "
//                   +cmbsoluong5.getSelectedItem()+ "  | Giá: "+(soluong[4]*tiennuoctt[4])+" |\n-------------------------------------------------------------------------\n Tổng Tiền: "+(soluong[0]*tiennuoctt[0]+soluong[1]*tiennuoctt[1]+soluong[2]*tiennuoctt[2]+soluong[3]*tiennuoctt[3]+soluong[4]*tiennuoctt[4])+"\n\nChúc Quý Khách Vui Vẻ"  
//                   
//               ,"Hóa Đơn"
//               ,JOptionPane.YES_NO_OPTION);
//            if(output == JOptionPane.YES_OPTION){
//        JOptionPane.showMessageDialog(null, "In Thanh Cong!!!");
//            }else if(output == JOptionPane.NO_OPTION){
//               jPanel2.show();
//            }
     //  }
    }
    private void inhoadon(String sqlsv){
        try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl= "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";
                Connection con=DriverManager.getConnection(dbUrl);
                //String link = "C:\\Users\\sniper dracula\\Documents\\NetBeansProjects\\Quancafe\\src\\quancafe\\report1.jrxml";
                JasperDesign jd= JRXmlLoader.load("C:\\Users\\sniper dracula\\Documents\\NetBeansProjects\\Quancafe\\src\\quancafe\\report1.jrxml");
                String sql = sqlsv;
                JRDesignQuery newq = new JRDesignQuery();
                newq.setText(sql);
                jd.setQuery(newq);
                JasperReport rs=JasperCompileManager.compileReport(jd);
                JasperPrint pri = JasperFillManager.fillReport(rs,null,con);
                JasperViewer.viewReport(pri);
                
                con.close();
        }catch(Exception ex){
                ex.printStackTrace();
        }
    }
    private void btninhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninhoadonActionPerformed
        int maban=Integer.parseInt(txtmaban.getText());
        int soloai=Integer.parseInt(cmbsoloainuoc.getSelectedItem().toString());
        //System.out.print(""+maban);
        //System.out.print(""+soloai);
        for (int i=1;i<=16;i++){
            if(maban==i){
                    String link="select * from QuanliQuan where MaBan="+i;
                    inhoadon(link);
                }
            }
       // new Quanli().show();
    }//GEN-LAST:event_btninhoadonActionPerformed
    public void xetsoluong(){
        //String sl[]={"00","01","02","03","04","05"};
        if (cmbsoloainuoc.getSelectedItem().equals(sl[0])){
            jLabel4.setVisible(false);
            jLabel9.setVisible(false);
            cmbmenu1.setVisible(false);
            cmbsoluong1.setVisible(false);
            jLabel5.setVisible(false);
            jLabel10.setVisible(false);
            cmbmenu2.setVisible(false);
            cmbsoluong2.setVisible(false);
            jLabel6.setVisible(false);
            jLabel11.setVisible(false);
            cmbmenu3.setVisible(false);
            cmbsoluong3.setVisible(false);
            jLabel7.setVisible(false);
            jLabel12.setVisible(false);
            cmbmenu4.setVisible(false);
            cmbsoluong4.setVisible(false);
            jLabel8.setVisible(false);
            jLabel13.setVisible(false);
            cmbmenu5.setVisible(false);
            cmbsoluong5.setVisible(false);
        }
        else if (cmbsoloainuoc.getSelectedItem().equals(sl[1])){
            jLabel4.setVisible(true);
            jLabel9.setVisible(true);
            cmbmenu1.setVisible(true);
            cmbsoluong1.setVisible(true);
            jLabel5.setVisible(false);
            jLabel10.setVisible(false);
            cmbmenu2.setVisible(false);
            cmbsoluong2.setVisible(false);
            jLabel6.setVisible(false);
            jLabel11.setVisible(false);
            cmbmenu3.setVisible(false);
            cmbsoluong3.setVisible(false);
            jLabel7.setVisible(false);
            jLabel12.setVisible(false);
            cmbmenu4.setVisible(false);
            cmbsoluong4.setVisible(false);
            jLabel8.setVisible(false);
            jLabel13.setVisible(false);
            cmbmenu5.setVisible(false);
            cmbsoluong5.setVisible(false);
        }
        else if(cmbsoloainuoc.getSelectedItem().equals(sl[2])){
            jLabel4.setVisible(true);
            jLabel9.setVisible(true);
            cmbmenu1.setVisible(true);
            cmbsoluong1.setVisible(true);
            jLabel5.setVisible(true);
            jLabel10.setVisible(true);
            cmbmenu2.setVisible(true);
            cmbsoluong2.setVisible(true);
            jLabel6.setVisible(false);
            jLabel11.setVisible(false);
            cmbmenu3.setVisible(false);
            cmbsoluong3.setVisible(false);
            jLabel7.setVisible(false);
            jLabel12.setVisible(false);
            cmbmenu4.setVisible(false);
            cmbsoluong4.setVisible(false);
            jLabel8.setVisible(false);
            jLabel13.setVisible(false);
            cmbmenu5.setVisible(false);
            cmbsoluong5.setVisible(false);
        }
        else if(cmbsoloainuoc.getSelectedItem().equals(sl[3])){
            jLabel4.setVisible(true);
            jLabel9.setVisible(true);
            cmbmenu1.setVisible(true);
            cmbsoluong1.setVisible(true);
            jLabel5.setVisible(true);
            jLabel10.setVisible(true);
            cmbmenu2.setVisible(true);
            cmbsoluong2.setVisible(true);
            jLabel6.setVisible(true);
            jLabel11.setVisible(true);
            cmbmenu3.setVisible(true);
            cmbsoluong3.setVisible(true);
            jLabel7.setVisible(false);
            jLabel12.setVisible(false);
            cmbmenu4.setVisible(false);
            cmbsoluong4.setVisible(false);
            jLabel8.setVisible(false);
            jLabel13.setVisible(false);
            cmbmenu5.setVisible(false);
            cmbsoluong5.setVisible(false);
        }
        else if(cmbsoloainuoc.getSelectedItem().equals(sl[4])){
            jLabel4.setVisible(true);
            jLabel9.setVisible(true);
            cmbmenu1.setVisible(true);
            cmbsoluong1.setVisible(true);
            jLabel5.setVisible(true);
            jLabel10.setVisible(true);
            cmbmenu2.setVisible(true);
            cmbsoluong2.setVisible(true);
            jLabel6.setVisible(true);
            jLabel11.setVisible(true);
            cmbmenu3.setVisible(true);
            cmbsoluong3.setVisible(true);
            jLabel7.setVisible(true);
            jLabel12.setVisible(true);
            cmbmenu4.setVisible(true);
            cmbsoluong4.setVisible(true);
            jLabel8.setVisible(false);
            jLabel13.setVisible(false);
            cmbmenu5.setVisible(false);
            cmbsoluong5.setVisible(false);
        }
        else {
        jLabel4.setVisible(true);
            jLabel9.setVisible(true);
            cmbmenu1.setVisible(true);
            cmbsoluong1.setVisible(true);
            jLabel5.setVisible(true);
            jLabel10.setVisible(true);
            cmbmenu2.setVisible(true);
            cmbsoluong2.setVisible(true);
            jLabel6.setVisible(true);
            jLabel11.setVisible(true);
            cmbmenu3.setVisible(true);
            cmbsoluong3.setVisible(true);
            jLabel7.setVisible(true);
            jLabel12.setVisible(true);
            cmbmenu4.setVisible(true);
            cmbsoluong4.setVisible(true);
            jLabel8.setVisible(true);
            jLabel13.setVisible(true);
            cmbmenu5.setVisible(true);
            cmbsoluong5.setVisible(true);
        }
    }
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (cmbsoloainuoc.getSelectedItem().equals(sl[0])){
            jLabel4.setVisible(true);
            jLabel9.setVisible(true);
            cmbmenu1.setVisible(true);
            cmbsoluong1.setVisible(true);
            cmbsoloainuoc.setSelectedIndex(1);
        }
        else if(cmbsoloainuoc.getSelectedItem().equals(sl[1])&& cmbmenu1.getSelectedIndex()!=0 && cmbsoluong1.getSelectedIndex()!=0){
            jLabel5.setVisible(true);
            jLabel10.setVisible(true);
            cmbmenu2.setVisible(true);
            cmbsoluong2.setVisible(true);
            cmbsoloainuoc.setSelectedIndex(2);
        }
        else if(cmbsoloainuoc.getSelectedItem().equals(sl[2])&& cmbmenu2.getSelectedIndex()!=0 && cmbsoluong2.getSelectedIndex()!=0){
            jLabel6.setVisible(true);
            jLabel11.setVisible(true);
            cmbmenu3.setVisible(true);
            cmbsoluong3.setVisible(true);
            cmbsoloainuoc.setSelectedIndex(3);
        }
        else if(cmbsoloainuoc.getSelectedItem().equals(sl[3]) && cmbmenu3.getSelectedIndex()!=0 && cmbsoluong3.getSelectedIndex()!=0){
            jLabel7.setVisible(true);
            jLabel12.setVisible(true);
            cmbmenu4.setVisible(true);
            cmbsoluong4.setVisible(true);
            cmbsoloainuoc.setSelectedIndex(4);
        }
        else if(cmbsoloainuoc.getSelectedItem().equals(sl[4]) && cmbmenu4.getSelectedIndex()!=0 && cmbsoluong4.getSelectedIndex()!=0){
            //else if(cmbsoloainuoc.getSelectedItem().equals(sl[1])){
            jLabel8.setVisible(true);
            jLabel13.setVisible(true);
            cmbmenu5.setVisible(true);
            cmbsoluong5.setVisible(true);
            cmbsoloainuoc.setSelectedIndex(5);
        //}
        }
    }//GEN-LAST:event_btnthemActionPerformed

    public void loadban1(){
        JButton bt[]={btn1,btn2,btn3,btn4,btn5,btn6,btn7,btn8,btn9,btn10,btn11,btn12,btn13,btn14,btn15,btn16};
        //this.btn1.BackColor = Color.Red;
        //btn1.setForeground(Color.red);
        try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl= "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";
                Connection con=DriverManager.getConnection(dbUrl);
                Statement so= con.createStatement();
                ResultSet rs = so.executeQuery("select MaBan,SoLoaiNuoc from QuanliQuan");
                int i=0;
                while(rs.next()){
                //System.out.print(""+rs.getInt(2));
                if (rs.getInt(2)!=0){
                    bt[i].setBackground(Color.GREEN);
                }
                else {
                    bt[i].setBackground(Color.BLACK);
                }
                i++;
                }
                con.close();
            //this.xetsoluong();
        }catch(Exception ex){
                ex.printStackTrace();
        }         
    }
    private void mahoa(){
            cmbmenu1.setEnabled(false);
            cmbsoluong1.setEnabled(false);
            cmbmenu2.setEnabled(false);
            cmbsoluong2.setEnabled(false);
            cmbmenu3.setEnabled(false);
            cmbsoluong3.setEnabled(false);
            cmbmenu4.setEnabled(false);
            cmbsoluong4.setEnabled(false);
            cmbmenu5.setEnabled(false);
            cmbsoluong5.setEnabled(false);
            btnthem.setEnabled(false);
            btnxoa.setEnabled(false);
            btnluu.setEnabled(false);
            btninhoadon.setEnabled(false);
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        mahoa();
        btnxanh.setBackground(Color.GREEN);
        this.loadban1();
    }//GEN-LAST:event_formWindowActivated
    private int xetluu(){
        JComboBox c[]={cmbmenu1,cmbmenu2,cmbmenu3,cmbmenu4,cmbmenu5};
        JComboBox d[]= {cmbsoluong1,cmbsoluong2,cmbsoluong3,cmbsoluong4,cmbsoluong5};
        String o="chua goi";
        String p="0";
        int kq=0;
        for (int i=0;i<5;i++){
//            System.out.print(""+c[i].getSelectedItem()+"\n"+d[i].);
            if((c[i].getSelectedItem().equals(o)==false && d[i].getSelectedItem().equals(p)) || (c[i].getSelectedItem().equals(o) && d[i].getSelectedItem().equals(p)==false)){
                JOptionPane.showMessageDialog(null, "Nhập Liệu Sai.Xin Nhập Lại");
                kq=1;
                jPanel2.setVisible(true);
                break;
            }
            else kq=2;
        }
        return kq;
    }
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        //xetluu();
        //System.out.print(""+xetluu());
        if (xetluu()==1){
            int u=Integer.parseInt(txtmaban.getText());
            jPanel2.show();
        }
        else {
            try{
            
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbUrl= "jdbc:sqlserver://SNIPERDRACULA\\SQLEXPRESS:1433;databaseName=QuanCafe;user=sa;password=sa2008";
                Connection con=DriverManager.getConnection(dbUrl);
                Statement so= con.createStatement();
                ResultSet rs = so.executeQuery("select * from QuanliQuan");
                
                int sln = cmbsoloainuoc.getSelectedIndex();
                //hang 1
                String menu1=cmbmenu1.getItemAt(cmbmenu1.getSelectedIndex());
                int sol1=cmbsoluong1.getSelectedIndex();
                //hang 2
                String menu2=cmbmenu2.getItemAt(cmbmenu2.getSelectedIndex());
                int sol2=cmbsoluong2.getSelectedIndex();
                //hang 3
                String menu3=cmbmenu3.getItemAt(cmbmenu3.getSelectedIndex());
                int sol3=cmbsoluong3.getSelectedIndex();
                //hang 3
                String menu4=cmbmenu4.getItemAt(cmbmenu4.getSelectedIndex());
                int sol4=cmbsoluong4.getSelectedIndex();
                //hang 3
                String menu5=cmbmenu5.getItemAt(cmbmenu5.getSelectedIndex());
                int sol5=cmbsoluong5.getSelectedIndex();
                String mb = txtmaban.getText();
                int kb=hamtam();
                String f="chua goi";
                int solu[]={sol1,sol2,sol3,sol4,sol5};
                String menui[]={menu1,menu2,menu3,menu4,menu5};
                
                String up ="update QuanliQuan set SoLoaiNuoc="+sln+",Loai1='"+menu1+"',SoLuong1="+sol1+",Loai2='"+menu2+"',SoLuong2="+sol2+",Loai3='"+menu3+"',SoLuong3="+sol3+",Loai4='"+menu4+"',SoLuong4="+sol4+",Loai5='"+menu5+"',SoLuong5="+sol5+ ",TongTien="+kb+" where MaBan="+mb;
                so.execute(up);
                
                
                
                    //else {cmbsoloainuoc.getItemAt(cmbsoloainuoc.getSelectedIndex());}
               // }
                for (int i=0;i<=4;i++){
                    if (menui[i].equals(f) && solu[i]==0){
                        String m= cmbsoloainuoc.getItemAt(i);
                        String op ="update QuanliQuan set SoLoaiNuoc='"+m+"'where MaBan="+mb;
                        so.execute(op);
                        //System.out.print("\na"+cmbsoloainuoc.getSelectedIndex());
                        break;
                    }
                    else {cmbsoloainuoc.getItemAt(cmbsoloainuoc.getSelectedIndex());}
                }
                JOptionPane.showMessageDialog(rootPane, "Lưu Thành Công!!!");
                
                 con.close();
                 this.xetsoluong();
                 unmahoa();
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnluuActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int output = JOptionPane.showConfirmDialog(null
               , "Ban co muon xoa"
               ,"Quan Li Quan Cafe"
               ,JOptionPane.YES_NO_OPTION);

            if(output == JOptionPane.YES_OPTION){
               
        cmbsoloainuoc.setSelectedIndex(0);
        cmbmenu1.setSelectedIndex(0);
        cmbsoluong1.setSelectedIndex(0);
        cmbmenu2.setSelectedIndex(0);
        cmbsoluong2.setSelectedIndex(0);
        cmbmenu3.setSelectedIndex(0);
        cmbsoluong3.setSelectedIndex(0);
        cmbmenu4.setSelectedIndex(0);
        cmbsoluong4.setSelectedIndex(0);
        cmbmenu5.setSelectedIndex(0);
        cmbsoluong5.setSelectedIndex(0);
        this.btnluuActionPerformed(evt);
        JOptionPane.showMessageDialog(null, "Xoa Thanh Cong!!!");
        //System.out.print("Yes selected.");
            }else if(output == JOptionPane.NO_OPTION){
               jPanel2.show();
            }
        //this.formWindowActivated(evt);
        this.loadban1();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btntrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrangActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=13;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=14;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=16;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=15;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=10;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=11;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=12;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=9;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=5;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=6;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=8;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=7;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=3;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=4;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=2;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        unmahoa();
        this.loadban();
        jPanel2.show();
        int i=1;
        txtmaban.setText(""+i);
        this.connectban(i);
        jLabel15.setText("Thông Tin Bàn Số "+i);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        // TODO add your handling code here:
        new Menu().show();
        this.hide();
    }//GEN-LAST:event_btndangxuatActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btninhoadon;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btntrang;
    private javax.swing.JButton btnxanh;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cmbmenu1;
    private javax.swing.JComboBox<String> cmbmenu2;
    private javax.swing.JComboBox<String> cmbmenu3;
    private javax.swing.JComboBox<String> cmbmenu4;
    private javax.swing.JComboBox<String> cmbmenu5;
    private javax.swing.JComboBox<String> cmbsoloainuoc;
    private javax.swing.JComboBox<String> cmbsoluong1;
    private javax.swing.JComboBox<String> cmbsoluong2;
    private javax.swing.JComboBox<String> cmbsoluong3;
    private javax.swing.JComboBox<String> cmbsoluong4;
    private javax.swing.JComboBox<String> cmbsoluong5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbtinhtien;
    private javax.swing.JTextField txtmaban;
    // End of variables declaration//GEN-END:variables
}
